### ISSUE TITLE
build polling frequency

### ISSUE THREAD

**Issue by hrishin** [fabric8io/jenkins-sync-plugin#14]
Right now `BuildSyncRunListener` polls every one second to OpenShift API when it receives the notification for new build trigger.
Recently we encounter [denial of service issue](https://github.com/openshiftio/openshift.io/issues/1648) for such kind of behavior on OpenShift API server.
Going to increase API poll frequency from 1 seconds to 5 seconds at least. 5 seconds benchmark works fine.

WDYT? @rupalibehera @gabemontero

**Comment by gabemontero** [comment]
+1 @hrishin
