### ISSUE TITLE
Fix 'Build' resource synchronization and update for Jenkins idler

### ISSUE THREAD

**Issue by hrishin** [fabric8io/jenkins-sync-plugin#19]
At present plugin synchronize the Build resource at the interval of 5 seconds. As part of synchronization, it looks like plugin updates the build's [start and completion time](https://github.com/fabric8io/jenkins-sync-plugin/blob/job-to-bc/src/main/java/io/fabric8/jenkins/openshiftsync/BuildSyncRunListener.java#L373) even if nothing has changed for the build.
This behavior is causing an [issues#130](https://github.com/fabric8-services/fabric8-jenkins-idler/issues/130) in the Jenkins idler, it's expecting to update the Build resource in Openshift only when there is change happen in the build with respect to the last one. Otherwise, don't update any resource in OpenShift if nothing happens.

*Tasks:*
- Confirm if build synchronization is really updating the build time. If yes then confirm the reason for such kind of behavior. This sync plugin is fork(downstream) of the upstream OpenShift Jenkins Plugin. Changin this behavior needs to consider the effect on upstream project as unifying efforts are going on between downstream and upstream project 

cc: @gabemontero @rupalibehera @aslakknutsen @pradeepto

**Comment by gabemontero** [comment]
Hey @hrishin 

Had something similar pop up in the first openshift online deployments.

We now have https://github.com/openshift/jenkins-sync-plugin/blob/master/src/main/java/io/fabric8/jenkins/openshiftsync/BuildSyncRunListener.java#L237-L271

And 

https://github.com/openshift/jenkins-sync-plugin/blob/master/src/main/java/io/fabric8/jenkins/openshiftsync/BuildSyncRunListener.java#L398-L402

I don't see that in the fabric job-to-bc version.

You do appear to have picked it up in https://github.com/fabric8io/jenkins-sync-plugin/pull/12

By the way, what is the status of that PR?  Did you have a chance to process the 2 bugs I found? and the solution I provided for one of those 2 bugs?

**Comment by hrishin** [comment]
> We now have https://github.com/openshift/jenkins-sync-plugin/blob/master/src/main/java/io/fabric8/jenkins/openshiftsync/BuildSyncRunListener.java#L237-L271
And
https://github.com/openshift/jenkins-sync-plugin/blob/master/src/main/java/io/fabric8/jenkins/openshiftsync/BuildSyncRunListener.java#L398-L402

@gabemontero awesome thanks! that's is what we are looking for.

> You do appear to have picked it up in #12

It should be there. _I got sidetracked on that PR. Going to fix it ASAP_

**Comment by pradeepto** [comment]
@hrishin Are you picking this up in this sprint? If so, please assign yourself.

**Comment by piyush-garg** [comment]
As #24 is merged, I am closing this.
