### ISSUE TITLE
Jenkins sync plugin creating two pipelines out of which one is incorrect

### ISSUE THREAD

**Issue by piyush-garg** [fabric8io/jenkins-sync-plugin#27]
Right now, Jenkins sync plugin is creating two pipelines when we create a git repo by `repo name` and create a build config with strategy Jenkins and name `app name` and source pointing to the repo created with `repo name`. This will work fine if `app name` and `repo name` are same. But if `app name` and `repo name` have different value then two pipelines get generated.

Maybe I am not clear in expressing the issue correctly. Feel free to correct me. The related issue on openshift.io is https://github.com/openshiftio/openshift.io/issues/3095

It may be possible that Jenkins sync plugin is not doing that but the initial observation seems like it is happening here.

cc @hrishin @rupalibehera @gabemontero

**Comment by gabemontero** [comment]
you may have already discovered this @piyush1594 , but looking at the job-to-bc branch, I see nothing in the io.fabric8.jenkins.openshiftsync.BuildConfigWatcher.upsertJob(BuildConfig) path or io.fabric8.jenkins.openshiftsync.BuildConfigToJobMap.getJobFromBuildConfig(BuildConfig) path that attempt to find WorkflowJobs whose name might line up with the repo name derived from the io.fabric8.openshift.api.model.GitBuildSource

Granted, this is my first time looking at this particular feature (my curiosity about it is why I looked in the first place ;-)), so maybe that coordination is elsewhere, but at first blush, I would think you would need such coordination to prevent the double create you have here.

Some coordination in io.fabric8.jenkins.openshiftsync.BuildDecisionHandler.shouldSchedule(Task, List<Action>) might be warranted as well.

Anyway, my 2 cents ... hopefully more helpful than not

**Comment by piyush-garg** [comment]
According to the info I have received, I have not reproduced that, if you create the repo in different org than your GitHub username, and you keep the build config name and repo name same then also it generates two pipelines.

**Comment by gabemontero** [comment]
OK, sure, their might be additional elements to the increased coordination I mentioned previously.

Yeah, bottom line, you need to reproduce with debug io.fabric8.jenkins.openshiftsync.BuildConfigWatcher.upsertJob(BuildConfig) that calls Jenkins.getItems(), Jenkins.getItemGroup(), etc. to see what the complete list is after the upstream git plugins create jobs, and see how you can leverage the metadata in the build config to fine the job the upstream git plugins create.

You might also have to fight timing windows where the build config events come *before* the upstream plugin processing happens, where you have to batch build config updates to make sure the other updates have occurred.

Sounds like a nasty one.

**Comment by piyush-garg** [comment]
What I have figured out is this happening here https://github.com/fabric8io/jenkins-sync-plugin/blob/job-to-bc/src/main/java/io/fabric8/jenkins/openshiftsync/PipelineJobListener.java#L249

Maybe wrong but from log message, it seems like it is happening here.

**Comment by gabemontero** [comment]
Yep that is the flow you all added where a job comes in from jenkins first, it will see if it maps to a build config in openshift.  Part of that flow upserts the BuildConfig, which could create a build config.

If the resulting build config create results in the BuildConfigWatcher getting a event then creating a job, there you go.

**Comment by piyush-garg** [comment]
As the changes are in prod now, I am closing this issue.
